server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

aws:
  region: eu-central-1
  s3:
    bucket-name:
      localTesting: viepovsky-test-bucket